//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by fs11.rc
//
#define VS_VERSION_INFO                 1

#define IDYESTOALL                      10
#define IDS_PROJNAME                    100
#define IDR_FOLDER                      101
#define IDS_DESCRIPTION                 101
#define IDR_VIEW                        102
#define IDS_COL_SIZE                    102
#define IDS_COL_TYPE                    103
#define IDS_COL_TIME                    104
#define IDS_COL_ATTR                    105
#define IDS_COL_NAME                    106
#define IDD_PROP_FILE                   106
#define IDD_PROP_VOLUME                 107
#define IDS_CLASSNAME                   107
#define IDS_INFOTIP                     108
#define IDS_ROOT                        109
#define IDS_FOLDER                      110
#define IDS_FILE                        111
#define IDS_COPYOF                      112
#define IDS_LINK                        113
#define IDI_APP                         201
#define IDC_TAB                         201
#define IDI_FOLDER                      202
#define IDC_APPLY                       202
#define IDC_APPICON                     203
#define IDC_FILENAME                    204
#define IDC_READONLY                    205
#define IDC_HIDDEN                      206
#define IDC_CREATED                     207
#define IDC_FILESIZEONDISK              208
#define IDC_TEXT                        208
#define IDR_ACCELERATOR                 209
#define IDC_FILESIZE                    209
#define IDC_NAME                        209
#define IDC_LOCATION                    210
#define IDD_COLLISION                   210
#define IDC_USEDSPACE                   210
#define IDI_REPLACE                     211
#define IDC_FREESPACE                   211
#define IDC_COMMENT                     211
#define IDR_MENU                        212
#define IDC_CAPACITY                    212
#define IDC_ARCHIVE                     212
#define IDC_TYPE                        213
#define IDR_VOLUMEDLG                   214
#define IDC_FILESYSTEM                  214
#define IDB_BLUE                        215
#define IDC_PIE                         215
#define IDB_RED                         216
#define IDR_DRIVE                       216
#define IDC_ADFFILE                     216
#define IDC_FLAGS                       216
#define IDB_NEWSHELL                    217
#define IDC_HARDDUMP                    217
#define IDC_HARDDISK                    217
#define IDD_NEWSHELL                    218
#define IDC_CHECK1                      218
#define IDC_HIGHDENSITY                 218
#define IDC_PRESETSIZE                  219
#define IDR_DROPHANDLER                 219
#define IDC_CUSTOMSIZE                  220
#define IDC_SIZESLIDER                  221
#define IDR_FOLDER_VISTA                221
#define IDC_DISKSIZE                    222
#define IDR_CONTEXTMENU                 222
#define IDC_FFS                         223
#define IDR_DATAOBJECT                  223
#define IDC_INTERNATIONAL               224
#define IDC_FILESIZE_LABEL              224
#define IDC_CACHE                       225
#define IDC_FILESIZEONDISK_LABEL        225
#define IDC_BOOT                        226
#define IDM_POPUP_FILE                  403
#define IDM_POPUP_FOLDER                404
#define IDM_POPUP_VIEW                  405
#define IDM_MENU_FILE                   406
#define IDM_POPUP_DELFILE               406
#define IDM_POPUP_DELETED               406
#define IDM_MENU_EDIT                   407
#define IDM_MENU_VIEW                   408
#define ID_EDIT_SELECTNONE              767
#define ID_FILE_EXPLORE                 771
#define IDS_FILES                       771
#define ID_EDIT_DELETE                  772
#define ID_EDIT_PROPERTIES              773
#define IDS_CONTAINS                    776
#define ID_VIEW_LARGEICONS              777
#define ID_VIEW_SMALLICONS              778
#define ID_VIEW_REPORT                  780
#define ID_VIEW_TILE                    781
#define ID_VIEW_CONTENT                 782
#define ID_EDIT_RENAME                  783
#define IDS_PASTE                       784
#define ID_EDIT_SELECTALL               785
#define ID_EDIT_INVERTSEL               786
#define ID_GO_UP                        787
#define ID_VIEW_CHANGE                  788
#define IDS_UNDELETE                    788
#define IDS_NEWFOLDER_DEFAULT           789
#define IDS_CONFIRMATION                790
#define IDS_GENERAL                     791
#define IDS_REPLACE                     792
#define IDS_DISKFULL                    793
#define IDS_WARNING                     794
#define IDS_OBJECTSELECTED              795
#define IDS_DESC_CUT                    796
#define IDS_DESC_COPY                   797
#define IDS_DESC_PASTE                  798
#define IDS_DESC_SELECTALL              799
#define IDS_DESC_DELETE                 800
#define IDS_DESC_RENAME                 801
#define IDS_DESC_PROP                   802
#define IDS_OPEN                        803
#define IDS_PROPERTIES                  804
#define IDS_DESC_OPEN                   805
#define IDS_VOLUME_CAPTION              806
#define IDS_FLOPDD                      807
#define IDS_FLOPHD                      808
#define IDS_HARDDISK                    809
#define IDS_HARDFILE                    810
#define IDS_UNKNOWN                     811
#define IDS_FFS                         812
#define IDS_OFS                         813
#define ID_HELP_HELPTOPICS              814
#define IDS_DELETEFILE                  816
#define IDS_DELETEFILES                 817
#define IDS_INSTALLERROR                818
#define IDS_VOLUMEREADONLY              819
#define ID_EDIT_UNDELETE                820
#define ID_VIEW_DELETEDFILES            821
#define IDS_DRIVEDESCRIPTION            822
#define IDS_SIZETOOBIG                  823
#define IDS_ERROR                       824
#define IDS_DISKLABEL                   825
#define IDS_DELETEDENTRY                826
#define IDS_DELETE                      827
#define IDS_RENAME                      828
#define IDS_DISKERROR                   829
#define IDS_FLAG_OFS                    830
#define IDS_FLAG_FFS                    831
#define IDS_FLAG_INTL                   832
#define IDS_FLAG_DIRCACHE               833
#define ID_VIEW_SORTNAME                834
#define IDS_COPY                        834
#define ID_VIEW_SORTSIZE                835
#define IDS_CUT                         835
#define ID_VIEW_SORTTYPE                836
#define ID_VIEW_SORTTIME                837
#define ID_VIEW_SORTATTRIBS             838
#define ID_VIEW_SPECIAL                 839
#define ID_NEWITEM_FOLDER               840
#define IDS_CMD_NEWFOLDER               841
#define ID_VIEW_REFRESH                 842


// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
